// MatterBridge.swift
// Copyright 2026 Monagle Pty Ltd

import Foundation
import MatterTypes
import MatterModel
import MatterCrypto
import MatterProtocol

/// High-level API for a Matter bridge device.
///
/// `MatterBridge` creates a root endpoint (0) and aggregator endpoint (1) at init,
/// then allows dynamic addition/removal of bridged device endpoints. It wraps
/// `EndpointManager`, `AttributeStore`, `SubscriptionManager`, and
/// `InteractionModelHandler` into a single facade.
///
/// ```swift
/// let bridge = MatterBridge(config: .init(
///     vendorName: "Acumen", productName: "Hub",
///     vendorId: 0xFFF1, productId: 0x8000
/// ))
///
/// let light = bridge.addDimmableLight(name: "Kitchen Pendant")
/// await light.setOnOff(true)
/// await light.setLevel(200)
///
/// let responses = try await bridge.handleIM(
///     opcode: .readRequest,
///     payload: requestData,
///     sessionID: 1,
///     fabricIndex: FabricIndex(rawValue: 1)
/// )
/// ```
public final class MatterBridge: @unchecked Sendable {

    // MARK: - Config

    /// Bridge configuration.
    public struct Config: Sendable {
        public let vendorName: String
        public let productName: String
        public let vendorId: UInt16
        public let productId: UInt16

        public init(
            vendorName: String = "SwiftMatter",
            productName: String = "Bridge",
            vendorId: UInt16 = 0xFFF1,
            productId: UInt16 = 0x8000
        ) {
            self.vendorName = vendorName
            self.productName = productName
            self.vendorId = vendorId
            self.productId = productId
        }
    }

    // MARK: - State

    public let config: Config
    public let store: AttributeStore
    public let endpoints: EndpointManager
    public let subscriptions: SubscriptionManager
    public let commissioningState: CommissioningState
    public let timedRequestTracker: TimedRequestTracker
    /// Event store for recording cluster events generated by commands.
    public let eventStore: EventStore
    /// Storage for group key sets (GroupKeyManagement cluster).
    public let groupKeySetStorage = GroupKeySetStorage()
    /// Group membership table — tracks per-fabric endpoint group assignments.
    public let groupMembershipTable = GroupMembershipTable()
    /// Buffer for reassembling chunked write requests across multiple UDP messages.
    public let chunkedWriteBuffer = ChunkedWriteBuffer()
    /// Buffer for reassembling chunked invoke requests across multiple UDP messages.
    public let chunkedInvokeBuffer = ChunkedInvokeBuffer()
    private let imHandler: InteractionModelHandler
    private var bridgedEndpoints: [EndpointID: BridgedEndpoint] = [:]

    // MARK: - Init

    public init(
        config: Config = Config(),
        commissioningState: CommissioningState? = nil,
        fabricStore: (any MatterFabricStore)? = nil,
        attributeStore: (any MatterAttributeStore)? = nil
    ) {
        self.config = config
        self.commissioningState = commissioningState ?? CommissioningState(fabricStore: fabricStore)
        self.store = AttributeStore(attributeStore: attributeStore)
        self.eventStore = EventStore()
        self.endpoints = EndpointManager(store: store)
        self.endpoints.eventStore = self.eventStore
        self.subscriptions = SubscriptionManager()
        self.timedRequestTracker = TimedRequestTracker()
        self.imHandler = InteractionModelHandler(
            endpoints: endpoints,
            subscriptions: subscriptions,
            store: store,
            timedRequestTracker: timedRequestTracker,
            chunkedWriteBuffer: chunkedWriteBuffer,
            chunkedInvokeBuffer: chunkedInvokeBuffer
        )

        setupRootEndpoint()
        setupAggregatorEndpoint()
    }

    // MARK: - Root + Aggregator Setup

    private func setupRootEndpoint() {
        let rootClusters: [ClusterID] = [
            .descriptor,
            .basicInformation,
            .generalCommissioning,
            .networkCommissioning,
            .generalDiagnostics,
            .operationalCredentials,
            .accessControl,
            .adminCommissioning,
            .groupKeyManagement,
            .timeSynchronization,
        ]
        let root = EndpointConfig(
            endpointID: EndpointID(rawValue: 0),
            deviceTypes: [(.rootNode, 1)],
            clusterHandlers: [
                // Per Matter spec §9.5.4.6, the Root Endpoint's PartsList MUST list all other
                // endpoints on the node. We include the aggregator (ep=1) here; bridged endpoints
                // are added dynamically when registerBridgedEndpoint() updates the store directly.
                DescriptorHandler(
                    deviceTypes: [(.rootNode, 1)],
                    serverClusters: rootClusters,
                    partsList: [EndpointManager.aggregatorEndpoint]
                ),
                BasicInformationHandler(
                    vendorName: config.vendorName,
                    vendorID: config.vendorId,
                    productName: config.productName,
                    productID: config.productId
                ),
                GeneralCommissioningHandler(commissioningState: commissioningState),
                NetworkCommissioningHandler(),
                GeneralDiagnosticsHandler(),
                OperationalCredentialsHandler(commissioningState: commissioningState),
                AccessControlHandler(commissioningState: commissioningState),
                AdminCommissioningHandler(commissioningState: commissioningState),
                GroupKeyManagementHandler(
                    commissioningState: commissioningState,
                    keySetStorage: groupKeySetStorage
                ),
                TimeSynchronizationHandler(),
            ]
        )
        endpoints.addEndpoint(root)
    }

    private func setupAggregatorEndpoint() {
        let aggClusters: [ClusterID] = [.descriptor]
        let aggregator = EndpointConfig(
            endpointID: EndpointManager.aggregatorEndpoint,
            deviceTypes: [(.aggregator, 1)],
            clusterHandlers: [
                DescriptorHandler(
                    deviceTypes: [(.aggregator, 1)],
                    serverClusters: aggClusters
                )
            ]
        )
        endpoints.addEndpoint(aggregator)
    }

    // MARK: - Add Endpoints

    /// Add a bridged dimmable light (OnOff + LevelControl + Groups + Identify + BridgedDeviceBasicInfo + Descriptor).
    @discardableResult
    public func addDimmableLight(
        name: String,
        uniqueID: String = "",
        onOffChanged: (@Sendable (Bool) -> Void)? = nil,
        levelChanged: (@Sendable (UInt8) -> Void)? = nil
    ) -> BridgedEndpoint {
        let epID = endpoints.nextEndpointID()
        let serverClusters: [ClusterID] = [.onOff, .levelControl, .groups, .identify, .bridgedDeviceBasicInformation, .descriptor]

        let config = EndpointConfig(
            endpointID: epID,
            deviceTypes: [(.bridgedNode, 1), (.dimmableLight, 1)],
            clusterHandlers: [
                OnOffHandler(onChange: onOffChanged),
                LevelControlHandler(onChange: levelChanged),
                GroupsHandler(groupMembershipTable: groupMembershipTable, commissioningState: commissioningState),
                IdentifyHandler(),
                BridgedDeviceBasicInfoHandler(nodeLabel: name, uniqueID: uniqueID),
                DescriptorHandler(
                    deviceTypes: [(.bridgedNode, 1), (.dimmableLight, 1)],
                    serverClusters: serverClusters
                )
            ]
        )
        endpoints.addEndpoint(config)
        return registerBridgedEndpoint(epID: epID, name: name)
    }

    /// Add a bridged on/off light (OnOff + Groups + Identify + BridgedDeviceBasicInfo + Descriptor).
    @discardableResult
    public func addOnOffLight(name: String, uniqueID: String = "") -> BridgedEndpoint {
        let epID = endpoints.nextEndpointID()
        let serverClusters: [ClusterID] = [.onOff, .groups, .identify, .bridgedDeviceBasicInformation, .descriptor]

        let config = EndpointConfig(
            endpointID: epID,
            deviceTypes: [(.bridgedNode, 1), (.onOffLight, 1)],
            clusterHandlers: [
                OnOffHandler(),
                GroupsHandler(groupMembershipTable: groupMembershipTable, commissioningState: commissioningState),
                IdentifyHandler(),
                BridgedDeviceBasicInfoHandler(nodeLabel: name, uniqueID: uniqueID),
                DescriptorHandler(
                    deviceTypes: [(.bridgedNode, 1), (.onOffLight, 1)],
                    serverClusters: serverClusters
                )
            ]
        )
        endpoints.addEndpoint(config)
        return registerBridgedEndpoint(epID: epID, name: name)
    }

    /// Add a bridged color temperature light (OnOff + LevelControl + ColorControl + Groups + Identify + BridgedDeviceBasicInfo + Descriptor).
    @discardableResult
    public func addColorTemperatureLight(
        name: String,
        uniqueID: String = "",
        onOffChanged: (@Sendable (Bool) -> Void)? = nil,
        levelChanged: (@Sendable (UInt8) -> Void)? = nil,
        colorTemperatureChanged: (@Sendable (UInt16) -> Void)? = nil
    ) -> BridgedEndpoint {
        let epID = endpoints.nextEndpointID()
        let serverClusters: [ClusterID] = [.onOff, .levelControl, .colorControl, .groups, .identify, .bridgedDeviceBasicInformation, .descriptor]

        let colorOnChange: (@Sendable (ColorControlChange) -> Void)? = colorTemperatureChanged.map { callback in
            { @Sendable change in
                if case .colorTemperature(let mireds) = change { callback(mireds) }
            }
        }
        let config = EndpointConfig(
            endpointID: epID,
            deviceTypes: [(.bridgedNode, 1), (.colorTemperatureLight, 1)],
            clusterHandlers: [
                OnOffHandler(onChange: onOffChanged),
                LevelControlHandler(onChange: levelChanged),
                ColorControlHandler(onChange: colorOnChange),
                GroupsHandler(groupMembershipTable: groupMembershipTable, commissioningState: commissioningState),
                IdentifyHandler(),
                BridgedDeviceBasicInfoHandler(nodeLabel: name, uniqueID: uniqueID),
                DescriptorHandler(
                    deviceTypes: [(.bridgedNode, 1), (.colorTemperatureLight, 1)],
                    serverClusters: serverClusters
                )
            ]
        )
        endpoints.addEndpoint(config)
        return registerBridgedEndpoint(epID: epID, name: name)
    }

    /// Add a bridged extended color light (OnOff + LevelControl + ColorControl + Groups + Identify + BridgedDeviceBasicInfo + Descriptor).
    @discardableResult
    public func addExtendedColorLight(
        name: String,
        uniqueID: String = "",
        onOffChanged: (@Sendable (Bool) -> Void)? = nil,
        levelChanged: (@Sendable (UInt8) -> Void)? = nil,
        colorTemperatureChanged: (@Sendable (UInt16) -> Void)? = nil,
        xyChanged: (@Sendable (UInt16, UInt16) -> Void)? = nil
    ) -> BridgedEndpoint {
        let epID = endpoints.nextEndpointID()
        let serverClusters: [ClusterID] = [.onOff, .levelControl, .colorControl, .groups, .identify, .bridgedDeviceBasicInformation, .descriptor]

        let colorOnChange: (@Sendable (ColorControlChange) -> Void)? = (colorTemperatureChanged != nil || xyChanged != nil) ? { @Sendable change in
            switch change {
            case .colorTemperature(let mireds): colorTemperatureChanged?(mireds)
            case .color(let x, let y): xyChanged?(x, y)
            default: break
            }
        } : nil
        let config = EndpointConfig(
            endpointID: epID,
            deviceTypes: [(.bridgedNode, 1), (.extendedColorLight, 1)],
            clusterHandlers: [
                OnOffHandler(onChange: onOffChanged),
                LevelControlHandler(onChange: levelChanged),
                ColorControlHandler(onChange: colorOnChange),
                GroupsHandler(groupMembershipTable: groupMembershipTable, commissioningState: commissioningState),
                IdentifyHandler(),
                BridgedDeviceBasicInfoHandler(nodeLabel: name, uniqueID: uniqueID),
                DescriptorHandler(
                    deviceTypes: [(.bridgedNode, 1), (.extendedColorLight, 1)],
                    serverClusters: serverClusters
                )
            ]
        )
        endpoints.addEndpoint(config)
        return registerBridgedEndpoint(epID: epID, name: name)
    }

    /// Add a bridged on/off plug-in unit (OnOff + Groups + Identify + BridgedDeviceBasicInfo + Descriptor).
    @discardableResult
    public func addOnOffPlugInUnit(
        name: String,
        uniqueID: String = "",
        onOffChanged: (@Sendable (Bool) -> Void)? = nil
    ) -> BridgedEndpoint {
        let epID = endpoints.nextEndpointID()
        let serverClusters: [ClusterID] = [.onOff, .groups, .identify, .bridgedDeviceBasicInformation, .descriptor]

        let config = EndpointConfig(
            endpointID: epID,
            deviceTypes: [(.bridgedNode, 1), (.onOffPlugInUnit, 1)],
            clusterHandlers: [
                OnOffHandler(onChange: onOffChanged),
                GroupsHandler(groupMembershipTable: groupMembershipTable, commissioningState: commissioningState),
                IdentifyHandler(),
                BridgedDeviceBasicInfoHandler(nodeLabel: name, uniqueID: uniqueID),
                DescriptorHandler(
                    deviceTypes: [(.bridgedNode, 1), (.onOffPlugInUnit, 1)],
                    serverClusters: serverClusters
                )
            ]
        )
        endpoints.addEndpoint(config)
        return registerBridgedEndpoint(epID: epID, name: name)
    }

    /// Add a bridged thermostat (Thermostat + Groups + Identify + BridgedDeviceBasicInfo + Descriptor).
    @discardableResult
    public func addThermostat(name: String, uniqueID: String = "") -> BridgedEndpoint {
        let epID = endpoints.nextEndpointID()
        let serverClusters: [ClusterID] = [.thermostat, .groups, .identify, .bridgedDeviceBasicInformation, .descriptor]

        let config = EndpointConfig(
            endpointID: epID,
            deviceTypes: [(.bridgedNode, 1), (.thermostat, 1)],
            clusterHandlers: [
                ThermostatHandler(),
                GroupsHandler(groupMembershipTable: groupMembershipTable, commissioningState: commissioningState),
                IdentifyHandler(),
                BridgedDeviceBasicInfoHandler(nodeLabel: name, uniqueID: uniqueID),
                DescriptorHandler(
                    deviceTypes: [(.bridgedNode, 1), (.thermostat, 1)],
                    serverClusters: serverClusters
                )
            ]
        )
        endpoints.addEndpoint(config)
        return registerBridgedEndpoint(epID: epID, name: name)
    }

    /// Add a bridged door lock (DoorLock + Groups + Identify + BridgedDeviceBasicInfo + Descriptor).
    @discardableResult
    public func addDoorLock(
        name: String,
        uniqueID: String = "",
        lockStateChanged: (@Sendable (UInt8) -> Void)? = nil
    ) -> BridgedEndpoint {
        let epID = endpoints.nextEndpointID()
        let serverClusters: [ClusterID] = [.doorLock, .groups, .identify, .bridgedDeviceBasicInformation, .descriptor]

        let config = EndpointConfig(
            endpointID: epID,
            deviceTypes: [(.bridgedNode, 1), (.doorLock, 1)],
            clusterHandlers: [
                DoorLockHandler(onChange: lockStateChanged),
                GroupsHandler(groupMembershipTable: groupMembershipTable, commissioningState: commissioningState),
                IdentifyHandler(),
                BridgedDeviceBasicInfoHandler(nodeLabel: name, uniqueID: uniqueID),
                DescriptorHandler(
                    deviceTypes: [(.bridgedNode, 1), (.doorLock, 1)],
                    serverClusters: serverClusters
                )
            ]
        )
        endpoints.addEndpoint(config)
        return registerBridgedEndpoint(epID: epID, name: name)
    }

    /// Add a bridged window covering (WindowCovering + Groups + Identify + BridgedDeviceBasicInfo + Descriptor).
    @discardableResult
    public func addWindowCovering(name: String, uniqueID: String = "") -> BridgedEndpoint {
        let epID = endpoints.nextEndpointID()
        let serverClusters: [ClusterID] = [.windowCovering, .groups, .identify, .bridgedDeviceBasicInformation, .descriptor]

        let config = EndpointConfig(
            endpointID: epID,
            deviceTypes: [(.bridgedNode, 1), (.windowCovering, 1)],
            clusterHandlers: [
                WindowCoveringHandler(),
                GroupsHandler(groupMembershipTable: groupMembershipTable, commissioningState: commissioningState),
                IdentifyHandler(),
                BridgedDeviceBasicInfoHandler(nodeLabel: name, uniqueID: uniqueID),
                DescriptorHandler(
                    deviceTypes: [(.bridgedNode, 1), (.windowCovering, 1)],
                    serverClusters: serverClusters
                )
            ]
        )
        endpoints.addEndpoint(config)
        return registerBridgedEndpoint(epID: epID, name: name)
    }

    /// Add a bridged fan (FanControl + Groups + Identify + BridgedDeviceBasicInfo + Descriptor).
    @discardableResult
    public func addFan(
        name: String,
        uniqueID: String = "",
        fanPercentChanged: (@Sendable (UInt8) -> Void)? = nil
    ) -> BridgedEndpoint {
        let epID = endpoints.nextEndpointID()
        let serverClusters: [ClusterID] = [.fanControl, .groups, .identify, .bridgedDeviceBasicInformation, .descriptor]

        let config = EndpointConfig(
            endpointID: epID,
            deviceTypes: [(.bridgedNode, 1), (.fan, 1)],
            clusterHandlers: [
                FanControlHandler(onChange: fanPercentChanged.map { callback in
                    { @Sendable change in
                        if case .percentSetting(let pct) = change { callback(pct) }
                    }
                }),
                GroupsHandler(groupMembershipTable: groupMembershipTable, commissioningState: commissioningState),
                IdentifyHandler(),
                BridgedDeviceBasicInfoHandler(nodeLabel: name, uniqueID: uniqueID),
                DescriptorHandler(
                    deviceTypes: [(.bridgedNode, 1), (.fan, 1)],
                    serverClusters: serverClusters
                )
            ]
        )
        endpoints.addEndpoint(config)
        return registerBridgedEndpoint(epID: epID, name: name)
    }

    /// Add a bridged contact sensor (BooleanState + Groups + Identify + BridgedDeviceBasicInfo + Descriptor).
    @discardableResult
    public func addContactSensor(name: String, uniqueID: String = "") -> BridgedEndpoint {
        let epID = endpoints.nextEndpointID()
        let serverClusters: [ClusterID] = [.booleanState, .groups, .identify, .bridgedDeviceBasicInformation, .descriptor]

        let config = EndpointConfig(
            endpointID: epID,
            deviceTypes: [(.bridgedNode, 1), (.contactSensor, 1)],
            clusterHandlers: [
                BooleanStateHandler(),
                GroupsHandler(groupMembershipTable: groupMembershipTable, commissioningState: commissioningState),
                IdentifyHandler(),
                BridgedDeviceBasicInfoHandler(nodeLabel: name, uniqueID: uniqueID),
                DescriptorHandler(
                    deviceTypes: [(.bridgedNode, 1), (.contactSensor, 1)],
                    serverClusters: serverClusters
                )
            ]
        )
        endpoints.addEndpoint(config)
        return registerBridgedEndpoint(epID: epID, name: name)
    }

    /// Add a bridged occupancy sensor (OccupancySensing + Groups + Identify + BridgedDeviceBasicInfo + Descriptor).
    @discardableResult
    public func addOccupancySensor(name: String, uniqueID: String = "") -> BridgedEndpoint {
        let epID = endpoints.nextEndpointID()
        let serverClusters: [ClusterID] = [.occupancySensing, .groups, .identify, .bridgedDeviceBasicInformation, .descriptor]

        let config = EndpointConfig(
            endpointID: epID,
            deviceTypes: [(.bridgedNode, 1), (.occupancySensor, 1)],
            clusterHandlers: [
                OccupancySensingHandler(),
                GroupsHandler(groupMembershipTable: groupMembershipTable, commissioningState: commissioningState),
                IdentifyHandler(),
                BridgedDeviceBasicInfoHandler(nodeLabel: name, uniqueID: uniqueID),
                DescriptorHandler(
                    deviceTypes: [(.bridgedNode, 1), (.occupancySensor, 1)],
                    serverClusters: serverClusters
                )
            ]
        )
        endpoints.addEndpoint(config)
        return registerBridgedEndpoint(epID: epID, name: name)
    }

    /// Add a bridged temperature sensor (TemperatureMeasurement + Groups + Identify + BridgedDeviceBasicInfo + Descriptor).
    @discardableResult
    public func addTemperatureSensor(name: String, uniqueID: String = "") -> BridgedEndpoint {
        let epID = endpoints.nextEndpointID()
        let serverClusters: [ClusterID] = [.temperatureMeasurement, .groups, .identify, .bridgedDeviceBasicInformation, .descriptor]

        let config = EndpointConfig(
            endpointID: epID,
            deviceTypes: [(.bridgedNode, 1), (.temperatureSensor, 1)],
            clusterHandlers: [
                TemperatureMeasurementHandler(),
                GroupsHandler(groupMembershipTable: groupMembershipTable, commissioningState: commissioningState),
                IdentifyHandler(),
                BridgedDeviceBasicInfoHandler(nodeLabel: name, uniqueID: uniqueID),
                DescriptorHandler(
                    deviceTypes: [(.bridgedNode, 1), (.temperatureSensor, 1)],
                    serverClusters: serverClusters
                )
            ]
        )
        endpoints.addEndpoint(config)
        return registerBridgedEndpoint(epID: epID, name: name)
    }

    /// Add a bridged humidity sensor (RelativeHumidityMeasurement + Groups + Identify + BridgedDeviceBasicInfo + Descriptor).
    @discardableResult
    public func addHumiditySensor(name: String, uniqueID: String = "") -> BridgedEndpoint {
        let epID = endpoints.nextEndpointID()
        let serverClusters: [ClusterID] = [.relativeHumidityMeasurement, .groups, .identify, .bridgedDeviceBasicInformation, .descriptor]

        let config = EndpointConfig(
            endpointID: epID,
            deviceTypes: [(.bridgedNode, 1), (.humiditySensor, 1)],
            clusterHandlers: [
                RelativeHumidityMeasurementHandler(),
                GroupsHandler(groupMembershipTable: groupMembershipTable, commissioningState: commissioningState),
                IdentifyHandler(),
                BridgedDeviceBasicInfoHandler(nodeLabel: name, uniqueID: uniqueID),
                DescriptorHandler(
                    deviceTypes: [(.bridgedNode, 1), (.humiditySensor, 1)],
                    serverClusters: serverClusters
                )
            ]
        )
        endpoints.addEndpoint(config)
        return registerBridgedEndpoint(epID: epID, name: name)
    }

    /// Add a bridged light sensor (IlluminanceMeasurement + Groups + Identify + BridgedDeviceBasicInfo + Descriptor).
    @discardableResult
    public func addLightSensor(name: String, uniqueID: String = "") -> BridgedEndpoint {
        let epID = endpoints.nextEndpointID()
        let serverClusters: [ClusterID] = [.illuminanceMeasurement, .groups, .identify, .bridgedDeviceBasicInformation, .descriptor]

        let config = EndpointConfig(
            endpointID: epID,
            deviceTypes: [(.bridgedNode, 1), (.lightSensor, 1)],
            clusterHandlers: [
                IlluminanceMeasurementHandler(),
                GroupsHandler(groupMembershipTable: groupMembershipTable, commissioningState: commissioningState),
                IdentifyHandler(),
                BridgedDeviceBasicInfoHandler(nodeLabel: name, uniqueID: uniqueID),
                DescriptorHandler(
                    deviceTypes: [(.bridgedNode, 1), (.lightSensor, 1)],
                    serverClusters: serverClusters
                )
            ]
        )
        endpoints.addEndpoint(config)
        return registerBridgedEndpoint(epID: epID, name: name)
    }

    // MARK: - Remove Endpoints

    /// Remove a bridged endpoint.
    public func removeEndpoint(_ endpointID: EndpointID) {
        endpoints.removeEndpoint(endpointID)
        bridgedEndpoints.removeValue(forKey: endpointID)
    }

    /// Remove a bridged endpoint by handle.
    public func removeEndpoint(_ endpoint: BridgedEndpoint) {
        removeEndpoint(endpoint.endpointID)
    }

    // MARK: - Internal

    private func registerBridgedEndpoint(epID: EndpointID, name: String) -> BridgedEndpoint {
        let bridged = BridgedEndpoint(
            endpointID: epID,
            name: name,
            store: store,
            subscriptions: subscriptions
        )
        bridgedEndpoints[epID] = bridged

        // Per Matter spec §9.5.4.6, the Root Endpoint (ep=0) PartsList MUST list ALL endpoints.
        // The Aggregator Endpoint (ep=1) PartsList MUST list all its bridged endpoints.
        // Update both in the AttributeStore now that we know the new endpoint ID.
        let allBridgedIDs = bridgedEndpoints.keys.sorted { $0.rawValue < $1.rawValue }
        let bridgedElements = allBridgedIDs.map { TLVElement.unsignedInt(UInt64($0.rawValue)) }

        // ep=0 PartsList: aggregator (ep=1) + all bridged endpoints
        let rootParts = [TLVElement.unsignedInt(UInt64(EndpointManager.aggregatorEndpoint.rawValue))] + bridgedElements
        store.set(
            endpoint: EndpointID(rawValue: 0),
            cluster: ClusterID.descriptor,
            attribute: DescriptorCluster.Attribute.partsList,
            value: .array(rootParts)
        )

        // ep=1 PartsList: all bridged endpoints
        store.set(
            endpoint: EndpointManager.aggregatorEndpoint,
            cluster: ClusterID.descriptor,
            attribute: DescriptorCluster.Attribute.partsList,
            value: .array(bridgedElements)
        )

        return bridged
    }

    // MARK: - IM Handling

    /// Handle an incoming Interaction Model message.
    ///
    /// This is the primary entry point for IM processing. It delegates to the
    /// `InteractionModelHandler` which routes to `EndpointManager` and
    /// `SubscriptionManager` as appropriate.
    ///
    /// Returns an `IMHandleResult` — either immediate response pairs or a chunked
    /// report context when the response is too large for a single UDP message.
    public func handleIM(
        opcode: InteractionModelOpcode,
        payload: Data,
        sessionID: UInt16,
        fabricIndex: FabricIndex,
        exchangeID: UInt16 = 0,
        requestContext: IMRequestContext? = nil
    ) async throws -> IMHandleResult {
        try await imHandler.handleMessage(
            opcode: opcode,
            payload: payload,
            sessionID: sessionID,
            fabricIndex: fabricIndex,
            exchangeID: exchangeID,
            requestContext: requestContext
        )
    }

    // MARK: - Subscription Reports

    /// Get pending subscription reports.
    public func pendingReports(now: Date = Date()) async -> [PendingReport] {
        await subscriptions.pendingReports(now: now)
    }

    /// Build ReportData chunk(s) for a pending subscription report.
    ///
    /// Reads the current values of all subscribed attributes and any new events since
    /// the last report, then encodes them as one or more `ReportData` chunks using
    /// `ReportDataChunker`. Fabric-scoped attributes are filtered to the subscription's
    /// fabric when `isFabricFiltered` was `true` at subscribe time.
    ///
    /// Returns `nil` if the subscription no longer exists; otherwise returns one or more
    /// chunks (most reports fit in a single chunk).
    public func buildReport(for report: PendingReport) async -> [ReportData]? {
        async let pathsTask = subscriptions.attributePaths(for: report.subscriptionID)
        async let eventPathsTask = subscriptions.eventPaths(for: report.subscriptionID)
        async let isFabricFilteredTask = subscriptions.isFabricFiltered(for: report.subscriptionID)
        async let fabricIndexTask = subscriptions.fabricIndex(for: report.subscriptionID)
        async let lastEventNumberTask = subscriptions.lastEventNumber(for: report.subscriptionID)
        async let dvFiltersTask = subscriptions.dataVersionFilters(for: report.subscriptionID)

        guard let paths = await pathsTask else {
            return nil
        }

        let eventPaths = await eventPathsTask ?? []
        let isFabricFiltered = await isFabricFilteredTask
        let fabricIndex = await fabricIndexTask
        let lastEventNumber = await lastEventNumberTask ?? EventNumber(rawValue: 0)
        let dvFilters = await dvFiltersTask

        let attributeReports = endpoints.readAttributes(
            paths,
            fabricFiltered: isFabricFiltered,
            fabricIndex: fabricIndex,
            dataVersionFilters: dvFilters
        )

        // Query events since the last reported event number (only if event paths were subscribed)
        let eventReports: [EventReportIB]
        if !eventPaths.isEmpty {
            let eventMin = EventNumber(rawValue: lastEventNumber.rawValue + 1)
            eventReports = await endpoints.readEvents(eventPaths, eventMin: eventMin.rawValue > 1 ? eventMin : nil)
        } else {
            eventReports = []
        }

        // Update last event number if we got new events
        if let lastReport = eventReports.compactMap({ $0.eventData }).last {
            await subscriptions.updateLastEventNumber(
                for: report.subscriptionID,
                to: lastReport.eventNumber
            )
        }

        // Chunk the report (suppressResponse=false — subscriber must ack each chunk)
        let chunker = ReportDataChunker()
        let chunks = chunker.chunk(
            subscriptionID: report.subscriptionID,
            attributeReports: attributeReports,
            eventReports: eventReports,
            suppressResponseOnFinal: false
        )
        return chunks
    }

    /// Mark a report as sent (resets timers).
    public func reportSent(subscriptionID: SubscriptionID, now: Date = Date()) async {
        await subscriptions.reportSent(subscriptionID: subscriptionID, now: now)
    }

    /// Expire stale subscriptions.
    public func expireStale(now: Date = Date()) async -> [SubscriptionID] {
        await subscriptions.expireStale(now: now)
    }

    // MARK: - Accessors

    /// All currently registered bridged endpoints.
    public var allBridgedEndpoints: [BridgedEndpoint] {
        Array(bridgedEndpoints.values)
    }

    /// Get a bridged endpoint by ID.
    public func bridgedEndpoint(for id: EndpointID) -> BridgedEndpoint? {
        bridgedEndpoints[id]
    }
}
