#!/usr/bin/env python3
# extract_test_vectors.py
# Copyright 2026 Monagle Pty Ltd
#
# Extracts cryptographic test vectors from connectedhomeip C header files
# and emits Swift source files for use in ReferenceTests.
#
# Usage:
#   python3 Tools/RefImpl/extract_test_vectors.py
#
# Reads from:  Tools/RefImpl/connectedhomeip/src/crypto/tests/*.h
# Writes to:   Tests/ReferenceTests/Fixtures/
#
# Run this script when updating the connectedhomeip version pin.
# The generated Swift files are checked in so tests run without the SDK.

import re
import sys
import os
import textwrap
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
REPO_DIR = SCRIPT_DIR / "connectedhomeip"
VECTORS_DIR = REPO_DIR / "src" / "crypto" / "tests"
OUTPUT_DIR = SCRIPT_DIR.parent.parent / "Tests" / "ReferenceTests" / "Fixtures"

COPYRIGHT = """\
// {filename}
// Copyright 2026 Monagle Pty Ltd
//
// AUTO-GENERATED by Tools/RefImpl/extract_test_vectors.py
// Source: connectedhomeip/src/crypto/tests/{source_file}
// Pin: {version}
//
// DO NOT EDIT manually — run extract_test_vectors.py to regenerate.

import Foundation
"""


def read_version() -> str:
    version_file = SCRIPT_DIR / "CONNECTEDHOMEIP_VERSION"
    if version_file.exists():
        return version_file.read_text().strip()
    return "unknown"


def extract_hex_array(c_source: str, array_name: str) -> list[int] | None:
    """Extract a C hex byte array by name, returning a list of ints."""
    # Match: static const uint8_t name[] = { 0xAA, 0xBB, ... };
    pattern = rf'(?:static\s+)?const\s+uint8_t\s+{re.escape(array_name)}\s*\[\s*\]\s*=\s*\{{([^}}]*)\}}'
    match = re.search(pattern, c_source, re.DOTALL)
    if not match:
        return None
    body = match.group(1)
    hex_values = re.findall(r'0x([0-9a-fA-F]{1,2})', body)
    return [int(v, 16) for v in hex_values]


def bytes_to_swift_array(data: list[int]) -> str:
    """Convert a list of ints to a Swift byte array literal."""
    if not data:
        return "[]"
    hex_strs = [f"0x{b:02x}" for b in data]
    return "[" + ", ".join(hex_strs) + "]"


def hex_to_swift_data(hex_str: str) -> str:
    """Convert a hex string to Swift Data from hex."""
    # Format: Data([0xAA, 0xBB, ...])
    if not hex_str:
        return "Data()"
    bytes_list = [f"0x{hex_str[i:i+2]}" for i in range(0, len(hex_str), 2)]
    return "Data([" + ", ".join(bytes_list) + "])"


def generate_hkdf_vectors_swift(version: str) -> str:
    """Generate Swift HKDF-SHA256 test vectors from RFC 5869 Appendix A."""
    # These are directly from RFC 5869 - canonical reference
    vectors = [
        {
            "name": "RFC5869_TC1",
            "description": "RFC 5869 Test Case 1 - Basic with SHA-256",
            "ikm":  "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b",
            "salt": "000102030405060708090a0b0c",
            "info": "f0f1f2f3f4f5f6f7f8f9",
            "length": 42,
            "okm":  "3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865",
        },
        {
            "name": "RFC5869_TC2",
            "description": "RFC 5869 Test Case 2 - Longer inputs/outputs",
            "ikm":  "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
                    "202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f"
                    "404142434445464748494a4b4c4d4e4f",
            "salt": "606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f"
                    "808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f"
                    "a0a1a2a3a4a5a6a7a8a9aaabacadaeaf",
            "info": "b0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecf"
                    "d0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeef"
                    "f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff",
            "length": 82,
            "okm":  "b11e398dc80327a1c8e7f78c596a49344f012eda2d4efad8a050cc4c19afa97c"
                    "59045a99cac7827271cb41c65e590e09da3275600c2f09b8367793a9aca3db71"
                    "cc30c58179ec3e87c14c01d5c1f3434f1d87",
        },
        {
            "name": "RFC5869_TC3",
            "description": "RFC 5869 Test Case 3 - Zero-length salt and info",
            "ikm":  "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b",
            "salt": "",
            "info": "",
            "length": 42,
            "okm":  "8da4e775a563c18f715f802a063c5a31b8a11f5c5ee1879ec3454e5f3c738d2d9d201395faa4b61a96c8",
        },
        {
            "name": "Matter_GroupKey",
            "description": "Matter spec §4.12.3 - GroupKey v1.0 info string (16-byte output)",
            "ikm":  "abababababababababababababababababababababababababababababababababab",  # 31 bytes — typical epoch key padded
            "salt": "0000000000000001",  # 8-byte big-endian compressed fabric ID
            "info": bytes("GroupKey v1.0", "utf-8").hex(),
            "length": 16,
            "okm":  None,  # computed at runtime — marked as needs_runtime_computation
        },
    ]

    lines = [COPYRIGHT.format(filename="HKDFTestVectors.swift", source_file="HKDF_SHA256_test_vectors.h", version=version)]
    lines.append("")
    lines.append("// MARK: - HKDF-SHA256 Test Vectors")
    lines.append("")
    lines.append("/// Test vectors for HKDF-SHA256, sourced from RFC 5869 Appendix A.")
    lines.append("struct HKDFTestVector: Sendable, CustomStringConvertible {")
    lines.append("    let name: String")
    lines.append("    let ikm: Data")
    lines.append("    let salt: Data")
    lines.append("    let info: Data")
    lines.append("    let outputLength: Int")
    lines.append("    let expectedOKM: Data")
    lines.append("    var description: String { name }")
    lines.append("}")
    lines.append("")
    lines.append("enum HKDFTestVectors {")
    lines.append("    static let all: [HKDFTestVector] = [")

    for v in vectors:
        if v["okm"] is None:
            continue  # skip vectors that need runtime computation
        salt_swift = hex_to_swift_data(v["salt"])
        info_swift = hex_to_swift_data(v["info"])
        lines.append(f'        HKDFTestVector(')
        lines.append(f'            name: "{v["name"]}",')
        lines.append(f'            ikm:  {hex_to_swift_data(v["ikm"])},')
        lines.append(f'            salt: {salt_swift},')
        lines.append(f'            info: {info_swift},')
        lines.append(f'            outputLength: {v["length"]},')
        lines.append(f'            expectedOKM: {hex_to_swift_data(v["okm"])}')
        lines.append(f'        ),')

    lines.append("    ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    version = read_version()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Write HKDF vectors (always available — from RFC 5869)
    hkdf_path = OUTPUT_DIR / "HKDFTestVectors.swift"
    hkdf_path.write_text(generate_hkdf_vectors_swift(version))
    print(f"Wrote: {hkdf_path}")

    # Attempt to extract from connectedhomeip if cloned
    if not VECTORS_DIR.exists():
        print(f"WARNING: {VECTORS_DIR} not found.")
        print("Run Tools/RefImpl/setup.sh first to clone connectedhomeip.")
        print("Skipping extraction of additional vectors.")
        return

    print(f"Extracting from: {VECTORS_DIR}")
    print("TODO: Implement full extraction from C headers (requires connectedhomeip clone)")


if __name__ == "__main__":
    main()
